"""main.py
This module is the entry point into the FastAPI application.
"""
from fastapi import FastAPI, status
from pydantic import BaseModel  # Import BaseModel for data validation

# Define your data models using Pydantic
class ProductRequestModel(BaseModel):
    name: str
    sku: str
    price: float
    stock: int
    description: str = None  # Optional field

class ProductResponseModel(BaseModel):
    id: str
    name: str
    sku: str
    price: float
    stock: int
    description: str = None

# Initialize the FastAPI application object
app = FastAPI(
    title="Inventory Service",
    description="Inventory Service for learning FastAPI",
    version="1.0.0",
)

@app.post("/products", response_model=ProductResponseModel, status_code=status.HTTP_201_CREATED)
def create_product(product: ProductRequestModel) -> ProductResponseModel:
    """This API will create a product."""
    
    # Here you would typically store the product in a database.
    # For demonstration, we are returning a mock response.
    
    return ProductResponseModel(
        id="1",  # In a real application, this would be generated by the database
        name=product.name,
        sku=product.sku,
        price=product.price,
        stock=product.stock,
        description=product.description,
    )
